/*  File generated by: Map Ed v0.98.5 */



extern const u16 bgPalette[256];
extern const u16 bgTiles[1856];
extern const u16 bgMap[880];
extern const u16 bgMap[2054];
extern const u16 bgMap[4096];
extern const u16 bgCollision[4096];
